// Все русские тексты подсказок в одном месте: источник правды — brain/PLAN.md §3.
// Отсюда их берёт мок-движок (E-02) и движок правил (E-09…E-12): дублировать тексты нельзя.

import type { Arrow, CalibrationStatus, ExerciseId, Joint, Phase, Severity } from './types';

/** Индексы точек MediaPipe Pose (33 landmark'а), чтобы не писать магические числа. */
export const LM = {
  nose: 0,
  leftShoulder: 11,
  rightShoulder: 12,
  leftElbow: 13,
  rightElbow: 14,
  leftWrist: 15,
  rightWrist: 16,
  leftHip: 23,
  rightHip: 24,
  leftKnee: 25,
  rightKnee: 26,
  leftAnkle: 27,
  rightAnkle: 28,
  leftFootIndex: 31,
  rightFootIndex: 32,
} as const;

export interface FormErrorDef {
  /** Стабильный код ошибки: по нему UI группирует статистику в итогах. */
  code: string;
  /** Конкретная подсказка на русском. «Движение не распознано» недопустимо. */
  message: string;
  /** Суставы, которые UI красит красным. */
  joints: Joint[];
  /** Куда двигать сустав; стрелку рисует UI. */
  arrow?: Arrow;
  severity: Severity;
  /** Фазы движения, на которых правило вообще имеет смысл проверять. */
  phases: Phase[];
  /** 1 — самая важная ошибка: при нескольких одновременно показываем одну. */
  priority: number;
  /** Штраф к оценке повторения (0..100). */
  penalty: number;
}

export const FORM_ERRORS: Record<ExerciseId, FormErrorDef[]> = {
  squat: [
    {
      code: 'shallow_depth',
      message: 'Сядь глубже — бедро до параллели с полом',
      joints: [LM.leftHip, LM.rightHip, LM.leftKnee, LM.rightKnee],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 30,
    },
    {
      code: 'knees_in',
      message: 'Разведи колени наружу, по линии носков',
      joints: [LM.leftKnee, LM.rightKnee],
      arrow: 'out',
      severity: 'bad',
      phases: ['down', 'bottom', 'up'],
      priority: 2,
      penalty: 25,
    },
    {
      code: 'torso_lean',
      message: 'Держи грудь выше, спина ровнее',
      joints: [LM.leftShoulder, LM.rightShoulder, LM.leftHip, LM.rightHip],
      arrow: 'up',
      severity: 'bad',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 20,
    },
    {
      code: 'asymmetry',
      message: 'Распредели вес на обе ноги',
      joints: [LM.leftKnee, LM.rightKnee],
      severity: 'warn',
      phases: ['bottom', 'up'],
      priority: 4,
      penalty: 15,
    },
    {
      code: 'too_fast',
      message: 'Медленнее — опускайся за 2 секунды',
      joints: [LM.leftHip, LM.rightHip],
      severity: 'warn',
      phases: ['up'],
      priority: 5,
      penalty: 10,
    },
  ],
  jumping_jack: [
    {
      code: 'arms_low',
      message: 'Подними руки выше головы',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'up',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'feet_narrow',
      message: 'Шире ноги — шире плеч',
      joints: [LM.leftAnkle, LM.rightAnkle],
      arrow: 'out',
      severity: 'bad',
      phases: ['bottom'],
      priority: 2,
      penalty: 25,
    },
    {
      code: 'not_synced',
      message: 'Руки и ноги — одновременно',
      joints: [LM.leftWrist, LM.rightWrist, LM.leftAnkle, LM.rightAnkle],
      severity: 'warn',
      phases: ['down', 'up'],
      priority: 3,
      penalty: 15,
    },
  ],
  lunge: [
    {
      code: 'knee_past_toe',
      message: 'Колено не дальше носка — шаг длиннее',
      joints: [LM.leftKnee, LM.leftFootIndex],
      arrow: 'in',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'back_knee_high',
      message: 'Опусти заднее колено ближе к полу',
      joints: [LM.rightKnee],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 2,
      penalty: 20,
    },
    {
      code: 'torso_lean',
      message: 'Корпус вертикально',
      joints: [LM.leftShoulder, LM.rightShoulder, LM.leftHip, LM.rightHip],
      arrow: 'up',
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 15,
    },
  ],
  arm_raise: [
    {
      code: 'elbows_bent',
      message: 'Выпрями руки полностью',
      joints: [LM.leftElbow, LM.rightElbow],
      arrow: 'up',
      severity: 'bad',
      phases: ['bottom', 'up'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'one_arm_low',
      message: 'Поднимай руки одновременно',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'up',
      severity: 'warn',
      phases: ['up', 'bottom'],
      priority: 2,
      penalty: 15,
    },
  ],
  high_knees: [
    {
      code: 'knees_low',
      message: 'Колени выше — до уровня пояса',
      joints: [LM.leftKnee, LM.rightKnee],
      arrow: 'up',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'lean_back',
      message: 'Не отклоняйся назад — держи корпус прямо',
      joints: [LM.leftShoulder, LM.rightShoulder, LM.leftHip, LM.rightHip],
      severity: 'warn',
      // Осанка, а не фаза шага: в быстром беге шаг короче антидребезга, поэтому и между шагами.
      phases: ['start', 'down', 'bottom', 'up'],
      priority: 2,
      penalty: 10,
    },
  ],
  knee_to_elbow: [
    {
      code: 'elbow_far',
      message: 'Тянись локтем к противоположному колену — до касания',
      joints: [LM.leftElbow, LM.rightElbow, LM.leftKnee, LM.rightKnee],
      arrow: 'in',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'knee_low',
      message: 'Подними колено выше — навстречу локтю',
      joints: [LM.leftKnee, LM.rightKnee],
      arrow: 'up',
      severity: 'warn',
      phases: ['bottom'],
      priority: 2,
      penalty: 15,
    },
  ],
  squat_press: [
    {
      code: 'shallow_depth',
      message: 'Сядь глубже — бедро до параллели с полом',
      joints: [LM.leftHip, LM.rightHip, LM.leftKnee, LM.rightKnee],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 30,
    },
    {
      code: 'press_low',
      message: 'Выпрями руки над головой до конца',
      joints: [LM.leftWrist, LM.rightWrist, LM.leftElbow, LM.rightElbow],
      arrow: 'up',
      severity: 'bad',
      phases: ['bottom', 'up'],
      priority: 2,
      penalty: 20,
    },
    {
      code: 'knees_in',
      message: 'Разведи колени наружу, по линии носков',
      joints: [LM.leftKnee, LM.rightKnee],
      arrow: 'out',
      severity: 'bad',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 20,
    },
  ],
  side_bend: [
    {
      code: 'shallow_bend',
      message: 'Наклонись ниже — тянись рукой к колену',
      joints: [LM.leftShoulder, LM.rightShoulder],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'lean_forward',
      message: 'Наклоняйся строго в сторону — не вперёд',
      joints: [LM.leftShoulder, LM.rightShoulder, LM.leftHip, LM.rightHip],
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 2,
      penalty: 15,
    },
    {
      code: 'hips_shift',
      message: 'Таз на месте — наклоняется только корпус',
      joints: [LM.leftHip, LM.rightHip],
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 10,
    },
  ],
  side_leg_raise: [
    {
      code: 'leg_low',
      message: 'Отведи ногу выше в сторону',
      joints: [LM.leftKnee, LM.rightKnee, LM.leftAnkle, LM.rightAnkle],
      arrow: 'out',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'torso_tilt',
      message: 'Не наклоняй корпус — в сторону уходит только нога',
      joints: [LM.leftShoulder, LM.rightShoulder],
      arrow: 'up',
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 2,
      penalty: 15,
    },
    {
      code: 'knee_bent',
      message: 'Нога прямая — не сгибай колено',
      joints: [LM.leftKnee, LM.rightKnee],
      severity: 'warn',
      phases: ['bottom'],
      priority: 3,
      penalty: 10,
    },
  ],
  side_lunge: [
    {
      code: 'shallow_side',
      message: 'Опустись ниже — бедро согнутой ноги к параллели',
      joints: [LM.leftHip, LM.rightHip, LM.leftKnee, LM.rightKnee],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'straight_leg_bent',
      message: 'Выпрями вторую ногу',
      joints: [LM.leftKnee, LM.rightKnee],
      severity: 'warn',
      phases: ['bottom'],
      priority: 2,
      penalty: 15,
    },
    {
      code: 'knee_in',
      message: 'Колено по линии носка — не заваливай внутрь',
      joints: [LM.leftKnee, LM.rightKnee],
      arrow: 'out',
      severity: 'bad',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 20,
    },
    {
      code: 'torso_lean',
      message: 'Держи грудь выше, спина ровнее',
      joints: [LM.leftShoulder, LM.rightShoulder, LM.leftHip, LM.rightHip],
      arrow: 'up',
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 4,
      penalty: 10,
    },
  ],
  jump_squat: [
    {
      code: 'shallow_depth',
      message: 'Сядь глубже перед прыжком — бедро к параллели',
      joints: [LM.leftHip, LM.rightHip, LM.leftKnee, LM.rightKnee],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'no_jump',
      message: 'Выпрыгни вверх — стопы отрываются от пола',
      joints: [LM.leftAnkle, LM.rightAnkle],
      arrow: 'up',
      severity: 'bad',
      phases: ['up'],
      priority: 2,
      penalty: 25,
    },
    {
      code: 'knees_in',
      message: 'Разведи колени наружу, по линии носков',
      joints: [LM.leftKnee, LM.rightKnee],
      arrow: 'out',
      severity: 'bad',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 20,
    },
  ],
  calf_raise: [
    {
      code: 'low_raise',
      message: 'Поднимись выше — на самые носки',
      joints: [LM.leftAnkle, LM.rightAnkle],
      arrow: 'up',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'too_fast',
      message: 'Медленнее — задержись наверху на секунду',
      joints: [LM.leftAnkle, LM.rightAnkle],
      severity: 'warn',
      phases: ['up'],
      priority: 2,
      penalty: 10,
    },
  ],
  cross_jack: [
    {
      code: 'no_cross',
      message: 'Скрести руки перед грудью',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'in',
      severity: 'bad',
      phases: ['up'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'feet_narrow',
      message: 'Шире ноги в прыжке — шире плеч',
      joints: [LM.leftAnkle, LM.rightAnkle],
      arrow: 'out',
      severity: 'warn',
      phases: ['bottom'],
      priority: 2,
      penalty: 15,
    },
    {
      code: 'arms_low',
      message: 'Руки в стороны на уровне плеч',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'up',
      severity: 'warn',
      phases: ['bottom'],
      priority: 3,
      penalty: 10,
    },
  ],
  arm_circles: [
    {
      code: 'arms_low',
      message: 'Держи руки на уровне плеч',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'up',
      severity: 'bad',
      phases: ['start', 'down', 'bottom', 'up'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'elbows_bent',
      message: 'Руки прямые — крути от плеча',
      joints: [LM.leftElbow, LM.rightElbow],
      severity: 'warn',
      phases: ['start', 'down', 'bottom', 'up'],
      priority: 2,
      penalty: 10,
    },
    {
      code: 'small_circles',
      message: 'Круги шире — рисуй кистью большой круг',
      joints: [LM.leftWrist, LM.rightWrist],
      severity: 'warn',
      phases: ['bottom'],
      priority: 3,
      penalty: 10,
    },
  ],
  boxing: [
    {
      code: 'short_punch',
      message: 'Выпрямляй руку до конца — удар в полную длину',
      joints: [LM.leftElbow, LM.rightElbow],
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'guard_down',
      message: 'Держи вторую руку у подбородка',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'up',
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 2,
      penalty: 15,
    },
  ],
  push_up: [
    {
      code: 'shallow_pushup',
      message: 'Опускайся ниже — грудь к полу',
      joints: [LM.leftElbow, LM.rightElbow],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'shoulders_uneven',
      message: 'Опускайся ровно — не заваливайся на одну руку',
      joints: [LM.leftShoulder, LM.rightShoulder],
      arrow: 'up',
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 2,
      penalty: 15,
    },
    {
      code: 'elbows_wide',
      message: 'Локти не в стороны — веди их назад, вдоль корпуса',
      joints: [LM.leftElbow, LM.rightElbow],
      arrow: 'in',
      severity: 'warn',
      phases: ['down', 'bottom', 'up'],
      priority: 3,
      penalty: 15,
    },
  ],
  // Планка на время лицом к камере: таз спереди не виден — следим за плечами и локтями.
  plank: [
    {
      code: 'shoulders_uneven',
      message: 'Держи плечи ровно — не заваливайся на бок',
      joints: [LM.leftShoulder, LM.rightShoulder],
      arrow: 'up',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 20,
    },
    {
      code: 'elbows_wide',
      message: 'Локти ставь под плечи',
      joints: [LM.leftElbow, LM.rightElbow],
      arrow: 'in',
      severity: 'warn',
      phases: ['bottom'],
      priority: 2,
      penalty: 15,
    },
  ],
  burpee: [
    {
      code: 'not_low',
      message: 'Опустись до упора лёжа — руки на полу, ноги назад',
      joints: [LM.leftShoulder, LM.rightShoulder],
      arrow: 'down',
      severity: 'bad',
      phases: ['bottom'],
      priority: 1,
      penalty: 25,
    },
    {
      code: 'no_jump',
      message: 'В конце выпрыгни вверх — руки над головой',
      joints: [LM.leftWrist, LM.rightWrist],
      arrow: 'up',
      severity: 'warn',
      phases: ['up'],
      priority: 2,
      penalty: 10,
    },
  ],
};

/** Подсказки калибровки: PLAN §2 и «Общие» из §3. */
export const CALIBRATION_HINTS: Record<CalibrationStatus, string> = {
  no_person: 'Повернись лицом к камере — тебя не видно',
  partial: 'Тебя не видно целиком — отойди назад',
  too_close: 'Отойди на шаг назад',
  too_far: 'Подойди ближе и встань в центр',
  dark: 'Слишком темно — добавь света',
  ok: 'Отлично, тебя видно целиком',
};

/**
 * Уточнённые подсказки калибровки: статус тот же, но причина конкретнее.
 * Например, partial бывает, когда обрезаны ноги, а бывает, когда человек стоит у края кадра.
 */
export const CALIBRATION_DETAIL_HINTS = {
  center: 'Встань в центр кадра',
  faceCamera: 'Повернись лицом к камере',
  showLegs: 'Отойди на шаг назад — нужно видеть ноги целиком',
  showHead: 'Отойди на шаг назад — голова не помещается в кадр',
  lostBody: 'Вернись в кадр — я тебя не вижу',
  lostJoints: 'Встань так, чтобы тебя было видно целиком',
} as const;

export function formErrorsFor(exercise: ExerciseId): FormErrorDef[] {
  return FORM_ERRORS[exercise];
}

export function findFormError(exercise: ExerciseId, code: string): FormErrorDef | undefined {
  return FORM_ERRORS[exercise].find((e) => e.code === code);
}
